<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSTkQwW6\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSTkQwW6/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerSTkQwW6.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerSTkQwW6\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerSTkQwW6\App_KernelProdContainer([
    'container.build_hash' => 'STkQwW6',
    'container.build_id' => '8d9dc98a',
    'container.build_time' => 1605852999,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSTkQwW6');
