<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'admin_index' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminRecetteController::index'], [], [['text', '/admin']], [], []],
    'admin_create' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminRecetteController::create'], [], [['text', '/admin/create']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
];
