<?php

namespace ContainerTqeCYzi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YXKWr5xService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YXKWr5x' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YXKWr5x'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'notification' => ['services', 'App\\Notification\\Notification', 'getNotificationService', true],
        ], [
            'notification' => 'App\\Notification\\Notification',
        ]);
    }
}
