<?php

namespace ContainerTqeCYzi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U9vO8dQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u9vO8dQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u9vO8dQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Admin\\AdminRecetteController::edit' => ['privates', '.service_locator.al7Yrdv', 'get_ServiceLocator_Al7YrdvService', true],
            'App\\Controller\\HomeController::contact' => ['privates', '.service_locator.YXKWr5x', 'get_ServiceLocator_YXKWr5xService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.al7Yrdv', 'get_ServiceLocator_Al7YrdvService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Notification\\Notification::notifyContact' => ['privates', '.service_locator.S6iF3Lw', 'get_ServiceLocator_S6iF3LwService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\Admin\\AdminRecetteController:edit' => ['privates', '.service_locator.al7Yrdv', 'get_ServiceLocator_Al7YrdvService', true],
            'App\\Controller\\HomeController:contact' => ['privates', '.service_locator.YXKWr5x', 'get_ServiceLocator_YXKWr5xService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.al7Yrdv', 'get_ServiceLocator_Al7YrdvService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Notification\\Notification:notifyContact' => ['privates', '.service_locator.S6iF3Lw', 'get_ServiceLocator_S6iF3LwService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\Admin\\AdminRecetteController::edit' => '?',
            'App\\Controller\\HomeController::contact' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'App\\Notification\\Notification::notifyContact' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Admin\\AdminRecetteController:edit' => '?',
            'App\\Controller\\HomeController:contact' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Notification\\Notification:notifyContact' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
