<?php

namespace ContainerTqeCYzi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Notification\Notification' shared autowired service.
     *
     * @return \App\Notification\Notification
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Notification/Notification.php';

        $container->services['App\\Notification\\Notification'] = $instance = new \App\Notification\Notification(($container->services['swiftmailer.mailer.default'] ?? $container->load('getSwiftmailer_Mailer_DefaultService')));

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Notification\\Notification', $container));

        return $instance;
    }
}
