<?php

namespace ContainerTqeCYzi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserRecetteControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\User\UserRecetteController' shared autowired service.
     *
     * @return \App\Controller\User\UserRecetteController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/User/UserRecetteController.php';

        $container->services['App\\Controller\\User\\UserRecetteController'] = $instance = new \App\Controller\User\UserRecetteController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['App\\Repository\\RecetteRepository'] ?? $container->load('getRecetteRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\User\\UserRecetteController', $container));

        return $instance;
    }
}
