<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIb3xqGb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIb3xqGb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIb3xqGb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIb3xqGb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIb3xqGb\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ib3xqGb',
    'container.build_id' => '484dd8d1',
    'container.build_time' => 1606275399,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIb3xqGb');
